### PR TITLE
Adds compressed payload support though an optional config 'nats.pull.subscription.payload.compression', supports zlib or none

### PR DESCRIPTION
**Pull request by stoddabr**
Discussed in https://github.com/nats-io/nats-spark-connector/issues/27

### CODE REVIEW

**Comment by jnmoyne** [comment]
Thanks for the contribution! Only requested changes are above and to make the option name and possible values the same as they are in V1, no need for them to change in V2.

**Comment by jnmoyne** [comment]
Also please if you could Sign-off the commit, thanks!

**Comment by stoddabr** [comment]
@jnmoyne I've added signoffs and changed the option to match v1

I changed it to match v2 since all other options changed. It feels weird to not have them match but you're the maintainer 🤷

**Comment by stoddabr** [comment]
I've thought more about spark options, please take a look at my proposal when you get a chance: https://github.com/nats-io/nats-spark-connector/issues/30

Would love to hear your feedback

**Review by jnmoyne — APPROVED** [review]
LGTM

**Pull request merged**
